// import type { Metadata } from "next";
// import "./globals.css";


// // import Header from "./components/header";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>

//         {children}
        
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body className="flex h-screen bg-gray-50"> 
        <Sidebar />

        <div className="flex flex-col flex-1 overflow-hidden">
          <Topbar />
          <main className="flex-1 overflow-auto p-3">{children}</main>
        </div>
      </body>
    </html>
  );
}

