import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { CartProvider } from "./context/giohangcontext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="vi">
      <body>
        {/* 🟢 Bao toàn bộ app bằng CartProvider */}
        <CartProvider>
          <Header />  {/* Header chỉ render 1 lần duy nhất */}
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
